### ISSUE TITLE
graphics lecture

### ISSUE THREAD

**Issue by ymaivali** [rstats-tartu/lectures#3]
I uploaded a file called graphics.Rmd into the rstats-tartu/lectures folder, which contains some of the code that I used today, and more. I recommend that you run the code until line 275 and see if you can make sense, what each line of code does. If not, look up the help for any insurgent function. 
Cheers, Ülo

PS! Its also an excellent resource for learning bad estonian.

**Comment by tpall** [comment]
Ülo see fail lõhkus raamatu! EEmalda sellest failist (yaml) pea! st kõik enne libraryite laadimist ja peatükkide pealkirjadest viska välja numbrid. muidu pean mina seda tegema.
Taavi

**Comment by ymaivali** [comment]
taavi, ma olen jälle need osalejate aadressid ära kaotaniud. kas ma saatsin sulle täiendatud aadressid? kui jah, saada mulle tagasi.
ülo

**Comment by tpall** [comment]
Graphics chapter fixed.
